core/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('todo/', include('todo.urls')),
    path('admin/', admin.site.urls),
]

todo/urls.py
from django.urls import path

from . import views as v

app_name = 'todo'
urlpatterns = [
    path('', v.index, name = 'index'),
    path('new/', v.new, name = 'new'),
    path('edit/<int:pk>/', v.edit, name='edit'),
    path('delete/<int:pk>/', v.delete, name='delete'),
    path('<int:pk>/', v.show, name='show')
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

class Tag(models.Model):
    title = models.CharField(max_length = 255, unique = True)

    def __str__(self):
        return self.title



class Todo(models.Model):
    title = models.CharField('標題', max_length = 255)
    content = models.TextField('內容', max_length = 500)
    status = models.BooleanField('已完成', default = False)
    tags = models.ManyToManyField(Tag, verbose_name = '標籤')
    creator = models.ForeignKey(User, on_delete = models.PROTECT, verbose_name = '建立者')

    def __str__(self):
        return self.title

todo/forms.py
from django.forms import ModelForm

from .models import Todo

class TodoModelForm(ModelForm):
    class Meta:
        model = Todo
        fields = '__all__'

todo/views.py
from django.shortcuts import render,get_object_or_404,redirect

from .models import Todo
from .forms import TodoModelForm

def index(request):
    todos = Todo.objects.all()
    return render(request, 'todo/index.html', {'todos':todos})

def new(request):
    form = TodoModelForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('todo:index')
    return render(request, 'todo/new.html', {
        'form': form
    })

def edit(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    form = TodoModelForm(request.POST or None,instance=todo)
    if form.is_valid():
        form.save()
        return redirect('todo:index')
    return render(request, 'todo/edit.html', {
        'form': form
    })

def delete(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    todo.delete()
    return redirect('todo:index')

def show(request, pk):
    todo = get_object_or_404(Todo, pk=pk)
    return render(request, 'todo/show.html', {
        'todo': todo
    })

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>TODO List</title>
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>

<body>
    <div class="container">
        {% block body %} {% endblock body %}
    </div>
</body>

</html>

templates/todo/edit.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% block body %}
    <div class="row">
        <div class="col">
            {% bootstrap_messages %}
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
<a class="btn btn-outline-warning" href="{% url 'todo:index' %}">back</a>
<h1>Edit</h1>
<hr>
{% endblock body %}

templates/todo/index.html
{% extends 'layout.html' %} {% block body %}
<h1>TODO List</h1>
<a href="{% url 'todo:new' %}" class="btn btn-outline-primary">new</a>
<hr> {% for todo in todos %}
<div class="row">
    <div class="col">
        <a href="{% url 'todo:edit' todo.id %}" class="btn btn-outline-info">edit</a>
        <a href="{% url 'todo:show' todo.id %}">
            <span>---{{todo.title}}---</span>
        </a>
        <a class="btn btn-outline-danger" href="{% url 'todo:delete' todo.id %}">delete</a>
        {% empty %}
        <a href="#" class="btn btn-outline-info disabled">No Todo</a>
    </div>
</div>
{% endfor %} {% endblock body %}

templates/todo/new.html
{% extends "layout.html" %}
{% load bootstrap4 %}
{% block body %}
    <div class="row">
        <div class="col">
            {% bootstrap_messages %}
            <form action="" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        Submit
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
<a class="btn btn-outline-warning" href="{% url 'todo:index' %}">back</a>
<h1>New</h1>
<hr>
{% endblock body %}

templates/todo/show.html
{% extends "layout.html" %} {% load bootstrap4 %} {% block body %}
<div class="row">
    <div class="col">
        <span>標題:{{todo.title}}</span>
        <br>
        <span>內容:{{todo.content}}</span>
        <br>
        <span>狀態:{{todo.status}}</span>
        <br>
        <a class="btn btn-outline-warning" href="{% url 'todo:index' %}">back</a>
    </div>
</div>
<hr> {% endblock body %}